"""add language_filter to quiz_sessions

Revision ID: 00a5d1eab02f
Revises: 40cefa3de40a
Create Date: 2026-05-22 10:37:51.959608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '00a5d1eab02f'
down_revision: Union[str, None] = '40cefa3de40a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_sessions', sa.Column('language_filter', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_sessions', 'language_filter')
    # ### end Alembic commands ###
