"""init

Revision ID: 262b4f1c694a
Revises: 
Create Date: 2026-05-20 11:09:27.587863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '262b4f1c694a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language', 'topic', name='uq_decks_language_topic')
    )
    op.create_index('idx_decks_language', 'decks', ['language'], unique=False)
    op.create_table('study_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_date', sa.Date(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('cards_seen', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_date')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('meaning', sa.String(), nullable=False),
    sa.Column('native', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_cards_deck', 'cards', ['deck_id'], unique=False)
    op.create_index('idx_cards_key', 'cards', ['idempotency_key'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('rows_parsed', sa.Integer(), nullable=True),
    sa.Column('rows_inserted', sa.Integer(), nullable=True),
    sa.Column('rows_skipped', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("direction IN ('1_only','2_only','3_only','4_only','1_and_2','all_available','random')", name='ck_quiz_sessions_direction'),
    sa.CheckConstraint("mode IN ('mcq','true_false','typing')", name='ck_quiz_sessions_mode'),
    sa.CheckConstraint("scope IN ('test','big_test')", name='ck_quiz_sessions_scope'),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("direction IN ('word_to_meaning','meaning_to_word','native_to_meaning','native_to_word')", name='ck_card_stats_direction'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'direction', name='uq_card_stats_card_direction')
    )
    op.create_index('idx_card_stats_card', 'card_stats', ['card_id'], unique=False)
    op.create_table('quiz_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('user_answer', sa.String(), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("direction IN ('word_to_meaning','meaning_to_word','native_to_meaning','native_to_word')", name='ck_quiz_answers_direction'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_answers')
    op.drop_index('idx_card_stats_card', table_name='card_stats')
    op.drop_table('card_stats')
    op.drop_table('quiz_sessions')
    op.drop_table('import_batches')
    op.drop_index('idx_cards_key', table_name='cards')
    op.drop_index('idx_cards_deck', table_name='cards')
    op.drop_table('cards')
    op.drop_table('users')
    op.drop_table('study_logs')
    op.drop_index('idx_decks_language', table_name='decks')
    op.drop_table('decks')
    # ### end Alembic commands ###
