"""add immersion_logs table

Revision ID: 3dfda45d7922
Revises: 632ed75fa4d5
Create Date: 2026-05-22 11:36:54.839677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3dfda45d7922'
down_revision: Union[str, None] = '632ed75fa4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('immersion_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("activity_type IN ('reading','listening','watching','speaking','writing','gaming','other')", name='ck_immersion_activity_type'),
    sa.CheckConstraint('duration_minutes > 0', name='ck_immersion_duration'),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name='ck_immersion_rating'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('immersion_logs')
    # ### end Alembic commands ###
