"""add essay_submissions table

Revision ID: 632ed75fa4d5
Revises: 00a5d1eab02f
Create Date: 2026-05-22 10:48:44.148540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '632ed75fa4d5'
down_revision: Union[str, None] = '00a5d1eab02f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('essay_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('evaluation', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('essay_submissions')
    # ### end Alembic commands ###
