"""add user settings table

Revision ID: c198f2e32ae5
Revises: 3dfda45d7922
Create Date: 2026-05-22 15:03:45.028226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c198f2e32ae5'
down_revision: Union[str, None] = '3dfda45d7922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
